### ISSUE TITLE
Window overlap with eyelink

### ISSUE THREAD

**Issue by ClementAbb** [Intrepid-2a/EyeTracking#10]
When the eyetracker object is created, an empty window is put on top of the experiment window (hiding it) and doesn't go away until a key press / another window opens e.g. for calibration or a similar event.

Possible leads so far:

> The localizeSetup function (or your version of the experiment) creates the main window object, used for the actual experiment (and for the LiveTrack calibration). The eye-tracker object then creates a second window object to pass to the IoHub so it can then make it's own third window object for calibration. Afterward, the second window object should be destroyed, and the main window should appear. It seems to me that the second window is not destroyed and somehow the functions to hide/show windows don't work as they're supposed to. Or maybe we should call them ourselves and not expect the IoHub stuff to do that.
If this is also solved by a keypress in the main experiment, that might be a clue as a keypress could change the focus window from the operating system's point of view, since the keyboard is linked to the first window object (I think), circumventing the hide/show window functions. So maybe test this with an extra keypress after the calibration? We can then look into how to make it more smooth later on.
Maybe the destruction of the second window can't happen because it's too soon after passing it on to IoHub, so a delay of half a second (maybe a second) could solve it. Or maybe this is not the way to get EyeLink and LiveTrack do the same calibration (we still need to scale the calibration area, btw, so it's not full screen, but more focussed around fixation).

**Comment by ClementAbb** [comment]
Got rid of this by simply not using __EL_window.

In particular I commented
```
        #self.__EL_window = win = visual.Window(resolution, 
        #                                       monitor    = mymonitor, 
        #                                       allowGUI   = True, 
        #                                       units      = 'pix', 
        #                                       fullscr    = True,
        #                                       color      = color,
        #                                       colorSpace = 'rgb', 
        #                                       screen
```

and

`#self.__EL_window.close()`

and replaced 

`self.io = self.launchHubServer(window = self.__EL_window, **devices_config)`

by
`self.io = self.launchHubServer(window = self.psychopyWindow, **devices_config)`

**Comment by thartbm** [comment]
Alright, that would mean that the default unit for the window object is pixels, which is not useful for the LiveTrack calibration and for having everything guaranteed in dva (even when we forget to manually set it). I could make a different main window object for the experiment run here... but that runs the risk of having differences between the experiments run at the two different labs.

I'd like to avoid this, by having sensible & identical units everywhere, except when throwing the window object to the IoHub code. Hence, centralized code is useful. It does create some additional hurdles, but only for calibration on the EyeLink, and not anywhere else. Hence, it seems logical to me to treat the EyeLink calibration as an exception, and not all other code. So _if_ it's achievable to solve this while using more sensible default units, that would be great.

Are we giving up on this?

**Comment by ClementAbb** [comment]
I was under the impression that this thing about units was solved because your code deals with coordinates and converts them directly (whereas in my implementation I checked whether the gaze coordinates were contained within a circle around the center of the screen).

**Comment by thartbm** [comment]
Well, I don't really know how the LiveTrack would work with a different unit window object (I'm at this point maybe we shouldn't try to find out). Plus, it's a matter of clean coding. The basic unit for the whole experiment is still dva, so shouldn't all units be dva? Bending the whole code for 1 exception seems strange and avoidable.

**Comment by ClementAbb** [comment]
My impression was wrong, the huge calibration dots are back if the window is in degrees.
The good news, however, is that the units can be changed at any point. So I can do:
```
win.units = 'pix'
tracker.initialize()
win.units = 'deg'
```

And then it works fine.

(should probably be implemented within the eyetracker code)

**Comment by thartbm** [comment]
Didn't know that was allowed!

To be clear, the calibration is done after the lines you just put in here?

**Comment by ClementAbb** [comment]
Yes calibration is done after:

```
colors = {'both'   : col_both,
          'back'   : col_back} 
## eyetracking
tracker = EyeTracker(tracker           = 'eyelink',
                     trackEyes         = [True, True],
                     fixationWindow    = 2.0,
                     minFixDur         = 0.2,
                     fixTimeout        = 3.0,
                     psychopyWindow    = win,
                     filefolder        = None,#eyetracking_path,
                     filename          = None,#et_filename+str(y),
                     samplemode        = 'average',
                     calibrationpoints = 5,
                     colors            = colors )                            

visual.TextStim(win,'screen 1').draw()
win.flip()
event.waitKeys()

## setup and initialize eye-tracker
win.units = 'pix'
tracker.initialize()
win.units = 'deg'

visual.TextStim(win,'screen 2').draw()
win.flip()
event.waitKeys()

tracker.calibrate()

visual.TextStim(win,'screen 3').draw()
win.flip()
event.waitKeys()
```

**Comment by thartbm** [comment]
Switching units in the initialization function now.

**Comment by ClementAbb** [comment]
Line 584 you have to change

`self.psychopyWindow.units = 'deg'`

into

`self.psychopyWindow.units = 'pix'`

and it will be completely solved.

**Comment by thartbm** [comment]
Oh man... done now. Please confirm so we can close this issue?

**Comment by ClementAbb** [comment]
Yes done
