### ISSUE TITLE
Eyelink calibration colors

### ISSUE THREAD

**Issue by ClementAbb** [Intrepid-2a/EyeTracking#12]
![20240409_151559](https://github.com/Intrepid-2a/EyeTracking/assets/154530279/bfcacd95-e765-4472-9a0a-932d3d477767)
![20240409_151610](https://github.com/Intrepid-2a/EyeTracking/assets/154530279/bd73261e-70dc-46ef-a542-8593213a1b08)

Sorry about the very bad image quality, but it should still be visible that the colors for the calibration window are off.

This bit is probably responsible:
```
         if 'back' in self.colors.keys():
            calibration['screen_background_color'] = [round((x + 1)*(255/2)) for x in self.colors['back']]+[255]
            calibration['target_attributes']['inner_color'] = [round((x + 1)*(255/2)) for x in self.colors['back']]+[255]
        else:
            calibration['screen_background_color'] = [round((x + 1)*(255/2)) for x in [0.5, 0.5, -1]]+[255] # close enough for most cases?
            calibration['target_attributes']['outer_color'] = [round((x + 1)*(255/2)) for x in [0.5, 0.5, -1]]+[255]

        if 'both' in self.colors.keys():
            calibration['target_attributes']['outer_color'] = [round((x + 1)*(255/2)) for x in self.colors['both']]+[255]
        else:
            calibration['target_attributes']['outer_color'] = [0,0,0,255] # black...
```

**Comment by thartbm** [comment]
After looking at the code again, I have no idea what goes wrong here, so first we need clues: I've added lines to print the input colors argument, and then also the self.colors argument, which should be set if the input is a dictionary (which it is).

**Comment by thartbm** [comment]
In the pasted output on the  path / filename issue, the input `colors` dict and `self.colors` are available (printed) and identical, so that's not the issue.

**Comment by thartbm** [comment]
Looked at some other messages about colors, and I hadn't noticed before that if you put psychopy colors in the dictionary that gets sent to iohub, it works. In the specs I had, it said it had to be RGB colors... so I removed conversion from psychopy to RGB colors, which might work now. If it does work, I can simplify the code a bit as well.

**Comment by ClementAbb** [comment]
That fixed it!
