### ISSUE TITLE
check standard data file when initializing EyeLink

### ISSUE THREAD

**Issue by thartbm** [Intrepid-2a/EyeTracking#14]
Right now the default file gets move to the indicated target location and name after the session is complete. However, we don't know what happens if the default file already exists. An existing file could be overwritten by the new file, which might mean a loss of data. It could also be that the new data file gets saved under a different name, but then the old file would get moved to the target location. This would mean we get the data messed up.

It would be good to at least check if the standard data file already exists when initializing the EyeLink, and issue a warning (with a pause) so that the experimenter can do what is necessary.

Alternatively, we could move, rename or even delete it in some predictable way. Here is a suggestion. We make a folder to move such pre-existing default files into, and we rename them with the date and time added. That way no data gets lost, and we know the file is from some session before that date and time. Most probably the immediately preceding one.

**Comment by thartbm** [comment]
This is more a solution for the target file issue I also raised, but this is exactly what I meant there. Since it works on your end: mind if I copy this code into the eye-tracker object? Will prevent potential issues for both the EyeLink and the LiveTrack side of things.

In the mean time, the standard data file "et_data.EDF" in the working directory might also exist, and this could cause trouble on your end, since it's EyeLink specific. This could also be solved in the eye-tracker object in some predictable, data-loss-preventing way. Could also be left to your version of the experiments. I'm open to whatever.

**Comment by ClementAbb** [comment]
Yes I got mixed up, for this I guess it doesn't hurt to check, if a file already exists it implies that something went very wrong in the previous run so that could at least raise a warning and move it somewhere so it's not overwritten (that's what happens with edf files).

**Comment by thartbm** [comment]
OK, neither should take long to implement. Especially the one you already solved.

**Comment by thartbm** [comment]
Added some lines for the default EyeLink file as well, on initialization. Lines 490-498 right now.

Check if this works? And is useful?

**Comment by ClementAbb** [comment]
Tried to run my testing script after putting a default edf file in the directory, it works.
