### ISSUE TITLE
check target file for both eye-trackers

### ISSUE THREAD

**Issue by thartbm** [Intrepid-2a/EyeTracking#15]
If, by some happenstance, we tell the eye-tracker object to put the eye-tracker data in a file that already exists, bad things might happen. In case of the EyeLink it might overwrite the existing file, or leave the default file in place. Either could result in data loss. In case of the LiveTrack, it could append the new data to the existing file, which would be fine, or it could overwrite the existing file, again resulting in data loss.

What if we check for existing files, and just add a number to it until we have a non-existing file, like we do for the calibration files?

**Comment by thartbm** [comment]
Added some lines (185-191) to make target files unique.

**Comment by ClementAbb** [comment]
Tried tu run my testing script after putting a default edf file in the directory, it works.
