### ISSUE TITLE
scale EyeLink calibration grid

### ISSUE THREAD

**Issue by thartbm** [Intrepid-2a/EyeTracking#17]
In order to do calibration on the most useful part of the screen, we could scale the calibration area down. I think by default, it uses 88% of the screen, but we only need a small area around the fixation, since we only want to check for fixation, so that's where we need high accuracy and hence calibration data. I think the minimum allowed is 33% of the screen width & height.

One way to go about it is to change the INI files on the EyeLink PC, but that means **all** experiments would have to use those values. So it would be better to pass the values to the EyeLink PC on initialization.

There seems to be no built-in function in IoHub to set this. But the eyelink implementation in IoHub does allow sending commands to the EyeLink, through `sendCommand()` method. This could be sufficient. It takes either just a key argument or both a key and value argument.

It would have to match these values from some of the *.INI files (CALIBR.INI ?):

```
calibration_area_proportion 0.88 0.83
validation_area_proportion 0.88 0.83
```

Which I'd both set to `0.33 0.33`

And perhaps:
```
calibration_corner_scaling 0.88
```

Which maybe we can turn of, so it would get a value of 1.

When this is done (or we give up on it) we could then make the calibration on the LiveTrack use the same points.

EDIT:
- There is also a `validation_corner_scaling` setting.
- In the CALIBR.INI file it says that setting the values for calibration also sets the same values for validation. Might be true for setting them through commands as well... we'll see?

**Comment by thartbm** [comment]
This is the `sendCommand()` function in the IOHub thing for EyeLink:

```
def sendCommand(self, key, value=None):
        """
        The sendCommand method sends an EyeLink command key and value to the EyeLink device.
        Any valid EyeLInk command can be sent using this method. However, not that
        doing so is a device dependent operation, and will have no effect on other
        implementations of the Common EyeTracker Interface, unless the other eye tracking
        device happens to support the same command, value format.
        
        If both key and value are provided, internally they are combined into a
        string of the form:
            
            "key = value" 
            
        and this is sent to the EyeLink device. If only key is provided, it is 
        assumed to include both the command name and any value or arguements 
        required by the EyeLink all in the one arguement, which is sent to the 
        EyeLink device untouched. 
        """
        try:
            if key in EyeTracker._COMMAND_TO_FUNCTION:
                return EyeTracker._COMMAND_TO_FUNCTION[key](*value)
            else:
                cmdstr=''
                if value is None:
                    cmdstr="{0}".format(key)
                else:
                    cmdstr="{0} = {1}".format(key,value)
                self._eyelink.sendCommand(cmdstr)    
                r= self._readResultFromTracker(cmdstr)
                print2err("[%s] result: %s"%(cmdstr,r))
                return EyeTrackerConstants.EYETRACKER_OK
        except Exception, e:
            return createErrorResult("IOHUB_DEVICE_EXCEPTION",
                    error_message="An unhandled exception occurred on the ioHub Server Process.",
                    method="EyeTracker.sendCommand", key=key,value=value, error=e)            
```

It's literally just passing them to the pylink method to send commands, so I should look up how that works, and which commands it accepts.

**Comment by thartbm** [comment]
The eye tracker object now has a function that scales the calibration area down: `setEyeLinkCalibrationScale()`. For now this just has the hardcoded values 0.35 0.35. It doesn't do corner scaling yet, first try something simple. In the end, this should also be done in the main functions, but there are other changes, so I didn't want to entangle everything.

To test if this works, after you do `tracker.initialize()` and before you do `tracker.calibrate()` please do: `tracker.setEyeLinkCalibrationScale()`.

**Comment by ClementAbb** [comment]
I works.

**Comment by thartbm** [comment]
Let's see... ask Lars what he thinks?

Patrick thinks we should calibrate only a few points close to fixation. So we could make this default, rather than an optional function, and maybe add some flexibility: a scale parameter when initializing the object? Or maybe set the distance of the dots to fixation?

Either the LiveTrack calibration has to be calculated from a scale to distance, or the EyeLink scale has to be calculated from distance to scale... but we can now also make the calibration more equal this way. I feel like we should determine what distance / scale we want, and feed each of the eye-trackers a setting that makes it comparable, rather than hard-code our particular hardware into the object.

**Comment by thartbm** [comment]
Put calibration are scaling as an argument for the EyeLink initialization function:

`tracker.initialize(calibrationScale=(0.35, 0.35))`

should do the trick. Test this?

I'll allow an arbitrary set of calibration points for the LiveTrack when initializing that, and set values that should match what you have.

**Comment by ClementAbb** [comment]
This works.

**Comment by thartbm** [comment]
OK, closing!
