### ISSUE TITLE
Monitor index

### ISSUE THREAD

**Issue by thartbm** [Intrepid-2a/EyeTracking#4]
The indices used may not be correct.
- Toronto: experiment should run on the 1st monitor (index 0)
- Glasgow: currently expects the experiment to run on the 1st monitor as well... would it make sense to allow different monitor indices for testing?

**Comment by thartbm** [comment]
Question: I was told the experimental setup (with the EyeLink) uses monitor index 0. But maybe that has changed and should be monitor index 1?

**Comment by ClementAbb** [comment]
We need it to be 1 yes.

**Comment by thartbm** [comment]
Alright: changed in the code.
