### ISSUE TITLE
set eye-tracker path and filename

### ISSUE THREAD

**Issue by thartbm** [Intrepid-2a/EyeTracking#8]
We need eye-tracker data to be stored away from the regular files, and with unique names... that have different extension for each of the eye-trackers (EyeLink: edf, LiveTrack: csv). Need different files for left and right hemisphere names.

Note: planned folder structure was changed slightly.

**Comment by ClementAbb** [comment]
About the folder structure, see what I wrote for the calibration, it really needs to be clarified somewhere.

**Comment by ClementAbb** [comment]
For now the edf file is still always saved in the current working directory (instead of where it should be).
See the file from my latest test:
[et_data.zip](https://github.com/Intrepid-2a/EyeTracking/files/14639137/et_data.zip)

**Comment by thartbm** [comment]
Not good. Which task was used to create this? I'm assuming the Distance task as it's the only one (so far) that tries to store any eye-tracking data. I will check how the file/path names get set.

IOhub should be able to handle this IMO. But a duct-tape solution could be to move the file over to where we want it after it has been downloaded to the experiment PC.

Otherwise, the file looks good to me, but has no messages / comments in it. Did you send any messages to the EyeLink?

**Comment by thartbm** [comment]
Perhaps the last file was somehow stored when doing a task that should not store any eye-tracker (like blind spot mapping).

I though line 492 (currently) took care of that:

```
        if self.storefiles:
            eyetracker_config['default_native_data_file_name'] = self.filename  # correct extention is added by IOhub
            eyetracker_config['local_edf_dir'] = self.filefolder                # otherwise this ends up in the main folder where the experiment itself lives
```

but I have now extended this with:

```
        else:
            print('no eyelink files should be stored')
            eyetracker_config['default_native_data_file_name'] = ''  # correct extention is added by IOhub
            eyetracker_config['local_edf_dir'] = ''                  # otherwise this ends up in the main folder where the experiment itself lives
```

This sets it to an empty filename, which might make it skip it. Otherwise we could set it to None to get some more of those NoneType warnings, or force each task that uses eye-tracking to provide a folder and filename.

**Comment by thartbm** [comment]
Hmmm. The message from the eye-tracking system about not storing any data indicates that the folder was not a string (probably set to `None`). So that part is correct... and that is either done by your version of blind spot mapping or the localizeSetup function. Which means the error is likely somewhere in the eyetracker object.

OK, it's actually in IoHub... the file name is their default filename, and it's in the default folder as well. This documentation page does not seem to mention a way to not store the data:

https://psychopy.org/api/iohub/device/eyetracker_interface/SR_Research_Implementation_Notes.html

The line: "default_native_data_file_name: et_data"

Maybe I'm missing something there? If you don;t see anything mentioned, maybe we should figure out what happens if you run another mapping thing: does that yield an error when trying to download? Does it overwrite the existing file? If it is just producing one useless file, we can probably just live with that. If it yields errors, I can add a line that removes that file... either before or after mapping (or both).

However, a few lines above that it mentions how to specify properties for calibration targets! :)

**Comment by thartbm** [comment]
I can't find any options in the documentation to _not_ create a file. I could dig in the actual code to see if there is some way to stop this, but I think we should move on to solve more pressing issues.

If you could test what happens if there is already a file present at the default location with the default name, that would be great. If it continues and it overwrites the file: no problem. If it crashes in some way, then we can write some code to prevent this (e.g. delete that default file when initializing an eyelink version of the eye-tracker object).

**Comment by ClementAbb** [comment]
It overwrites the file, still I don't like this file being there so I would prefer either deleting it or saving that as actual data.

**Comment by thartbm** [comment]
Do you want the eye-tracker object to delete it, or the blind spot mapping task? Neither is great, so I don't care too much, but it seems a bit neater to me to do it in the eye-tracker object, because that's _supposed_ to handle it to begin with.

If you prefer saving it, it should get a proper folder and filename as input.

**Comment by ClementAbb** [comment]
You could have a check when closing the eye tracker object, looking for a file in the current working directory called "et_data.EDF" and deleting it if it exists.

**Comment by thartbm** [comment]
If that exists, you could also save the data with a proper filename / path and it would all still work. Will try implementing today.

**Comment by thartbm** [comment]
This should be done now. Want to check?

**Comment by ClementAbb** [comment]
It's still trying to create the file at a given location so still crashing if I try to give a specific file name/location, but deletion works if I set them to None

**Comment by thartbm** [comment]
OK. For ease of use, perhaps the eye-tracker object should set them to None if either one is not provided?

**Comment by ClementAbb** [comment]
What I imagine would work given this situation is letting it create the default file in all cases, then change the behavior when closing depending on the parameters:
- Rename the file with custom name if provided
- Move the file to custom location if provided
- Delete the file if no custom name and/or location?

**Comment by thartbm** [comment]
Wait, does that mean that it never uses the file or folder name, even when provided?

It's now 1) explicitly set to None on initializing the IoHub thing if both arguments are at their default value of None, and 2) it removes the standard file (if it exists) in the shutdown function.

But if the file is still in the standard name/location even when the path and filename are specified, that would remove good data as well...

**Comment by ClementAbb** [comment]
Specifying a file or folder name right now just makes it crash for reasons unknown (maybe changing to absolute path could solve this, probably not), however we do know that without saying anything during initialization it will just create a file with the default name in the current working directory.  I say just let it do this, and deal with this file in an appropriate manner (renaming and moving or deleting) when closing the object, given the parameters provided. Seems to solve everything to me.

**Comment by ClementAbb** [comment]
> Crashes when specifying any type of folder / filename are new to me. Must have missed that.
See https://github.com/Intrepid-2a/EyeTracking/issues/11

> If we can't specify a folder and filename for the eye-tracker object to use, the eye-tracker object can't move the default file to that folder & filename.
I don't see why that would be the case, it's not a matter of what arguments you are specifying but of how/when you use them. In that case instead of doing whatever the code trying to do now (tell iohub to create the logfiles at specific location with specific name, which so far doesn't work), we let iohub do what it wants (create the default file at the default location, which does work even too well since we can't prevent it even when we want to) and correct that later (by renaming and moving the file using the specified parameters, or removing it when no parameter is specified).

**Comment by ClementAbb** [comment]
> 1) explicitly set to None on initializing the IoHub thing if both arguments are at their default value of None

This now makes it crash when I try to instantiate the object with both values at None:

```
tracker = EyeTracker(tracker           = 'eyelink',
                     trackEyes         = [True, True],
                     fixationWindow    = 2.0,
                     minFixDur         = 0.2,
                     fixTimeout        = 3.0,
                     psychopyWindow    = win,
                     filefolder        = None,#eyetracking_path,
                     filename          = None,#et_filename+str(y),
                     samplemode        = 'average',
                     calibrationpoints = 5,
                     colors            = colors )   
```

```
PS C:\Users\clementa\Desktop\templeton_gh\Distance> & "C:\Program Files\PsychoPy_2022\python.exe" .\ET_for_glasgow_test.py
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
{'both': [1, 1, 1], 'back': [0.55, 0.45, -1.0]}
{'both': [1, 1, 1], 'back': [0.55, 0.45, -1.0]}
NOTE: not storing any files since filefolder is not a string
None
None
False
no eyelink files should be stored
ERROR: DEVICE CONFIG ERRORS FOUND! IOHUB NOT LOADING DEVICE: psychopy.iohub.devices.eyetracker.hw.sr_research.eyelink
not_found count 1:
        ('local_edf_dir', None)


## Device was not started by the ioHub Server: eyetracker.hw.sr_research.eyelink.EyeTracker
Error during device creation ....
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 716, in createNewMonitoredDevice
    raise ioHubError('Device config validation failed')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Device config validation failed',)

Error during device creation ....
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 716, in createNewMonitoredDevice
    raise ioHubError('Device config validation failed')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Device config validation failed',)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 642, in _addDevices
    self.createNewMonitoredDevice(dev_cls_name, dev_conf)
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 721, in createNewMonitoredDevice
    raise ioHubError('Error during device creation ....')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Error during device creation ....',)

GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
Traceback (most recent call last):
  File ".\ET_for_glasgow_test.py", line 75, in <module>
    tracker.calibrate()
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 620, in __EL_calibrate
    result = self.tracker.runSetupProcedure()
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\client\__init__.py", line 153, in __getattr__
    raise AttributeError(self, name)
AttributeError: (<psychopy.iohub.client.ioHubDeviceView object at 0x0000021EB486FAF0>, 'runSetupProcedure')
Exception ignored in: <function EyeTracker.__del__ at 0x0000021EA6E3ECA0>
Traceback (most recent call last):
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 1300, in __del__
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 1277, in __EL_shutdown
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 1007, in __EL_stopcollecting
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\client\__init__.py", line 153, in __getattr__
AttributeError: (<psychopy.iohub.client.ioHubDeviceView object at 0x0000021EB486FAF0>, 'setRecordingState')
PS C:\Users\clementa\Desktop\templeton_gh\Distance> 0.8477      WARNING         Monitor specification not found. Creating a temporary one...
```

**Comment by thartbm** [comment]
Oh man. Going to start up the main machine and change this code anyway. I'm thinking the first thing to do is to get this right. And I'll try to just not set it at all.

**Comment by thartbm** [comment]
Actually, is this the same issue as the other one on EDF files? The other one now has the more recent comments. Can we close this one?

**Comment by ClementAbb** [comment]
The way I see it they are two issues with the same solution (handle it when closing the object).

Couple of minor things and a major one:

Missing closing apostrophe at line 1301

`src = 'et_data.EDF`

Had to comment lines 516-517, any value you try to specify to eyetracker_config['default_native_data_file_name'] and eyetracker_config['local_edf_dir'] results in an error.

The new __EL_shutdown throws this error:

```
PS C:\Users\clementa\Desktop\templeton_gh\Distance> & "C:\Program Files\PsychoPy_2022\python.exe" .\ET_for_glasgow_test.py
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
../data/distance/eyetracking/test/
test_dist_LH_2
True
[0.55, 0.45, -1.0]
[1, 1, 1]
displayAPI: init_net() start use_tcp_only=0
displayAPI: Connecting
IOHUB_DEVICE_EXCEPTION.Error: Could not retrieve sample rate modes from EyeLink Host. EyeTracker.setSamplingRate None
ERROR: setEyesToTrack: Failed to get supported modes.
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\visual\shape.py:251: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if value == "circle":
2.3942  WARNING         Monitor specification not found. Creating a temporary one...
Calibration returned:  {'message': 'validation_result: 0.50 3.89 -10.81  0.33 0.20 -1.27', 'result': 1000}
file_size = 208273
total_wbytes = 208273
displayAPI: Disconnect
ioHub Server Process Completed With Code:  0
Exception ignored in: <function EyeTracker.__del__ at 0x0000022CA7ADED30>
Traceback (most recent call last):
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 1330, in __del__
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 1295, in __EL_shutdown
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 1025, in __EL_stopcollecting
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\client\__init__.py", line 73, in __call__
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\client\__init__.py", line 1154, in _sendToHubServer
ImportError: sys.meta_path is None, Python is likely shutting down
```

Doesn't seem to be specific to custom file names/paths, it does the same when both are set to None or even if I comment out the whole process of renaming/moving:

```
        #if self.storefiles:
        #    src = 'et_data.EDF'
        #    dst = os.path.join(self.filefolder, self.filename + '.EDF')
        #
        #    # os.rename can use relative paths:
        #    os.rename(src, dst)
        #
        #else:
        #    if os.path.isfile('et_data.EDF'):
        #        os.remove('et_data.EDF')
```


In fact the renaming/moving/deleting the default file doesn't work either so I'm guessing the crash occurs before that.

I don't remember it doing that in the past. No idea what is happening here.

**Comment by thartbm** [comment]
Added the closing quotation mark and commented out 516 & 517.

Two things seem to happen. First, I should have foreseen: your experiment runs the shutdown function. No need to run it again when the object gets destroyed. And if we decide to keep that, the shutdown function should check if it still needs to do stuff or not.

Second, I didn't know about: when __del__ is called (as the object is being destroyed) relative paths no longer work, which has something to do with Python shutting down (probably won't be the case when the experiment is run as a function). So, if we decide to have this back-up function, it should at least use absolute paths, but I expect more issues with doing stuff during garbage collection. So maybe let's forget about this for now.

Either way, I'll remove the __del__ function for now, so we can first get the shutdown function to work properly. 

For that: does the experiment create an `et_data.EDF` file? One hypothesis is that the download of that file is handed off to a different thread, such that the shutdown function finishes before the file it's trying to move actually exists. I've added some print debug statements to check this.

**Comment by ClementAbb** [comment]
Shutdown function: should I not call it? That's not a problem, I just need to know.

Here is the current result if I run my testing script with None for file name/path:
```
PS C:\Users\clementa\Desktop\templeton_gh\Distance> & "C:\Program Files\PsychoPy_2022\python.exe" .\ET_for_glasgow_test.py
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
NOTE: not storing any files since filefolder is not a string
None
None
False
displayAPI: init_net() start use_tcp_only=0
displayAPI: Connecting
IOHUB_DEVICE_EXCEPTION.Error: Could not retrieve sample rate modes from EyeLink Host. EyeTracker.setSamplingRate None
ERROR: setEyesToTrack: Failed to get supported modes.
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\visual\shape.py:251: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if value == "circle":
TypeError: an integer is required (got type NoneType)
TypeError: an integer is required (got type NoneType)
2.5004  WARNING         Monitor specification not found. Creating a temporary one...
Calibration returned:  {'message': 'validation_result: 0.58 -0.33 17.83  0.24 1.35 4.85', 'result': 1000}
file_size = 210969
total_wbytes = 210969
displayAPI: Disconnect
ioHub Server Process Completed With Code:  0
['et_data.EDF']
['et_data.EDF']
```

And the edf file gets deleted at the end.

If I run it with a specified name/path:

```
PS C:\Users\clementa\Desktop\templeton_gh\Distance> & "C:\Program Files\PsychoPy_2022\python.exe" .\ET_for_glasgow_test.py
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
../data/distance/eyetracking/test/
test_dist_LH_3
True
displayAPI: init_net() start use_tcp_only=0
displayAPI: Connecting
IOHUB_DEVICE_EXCEPTION.Error: Could not retrieve sample rate modes from EyeLink Host. EyeTracker.setSamplingRate None
ERROR: setEyesToTrack: Selected sample rate is not supported!
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\visual\shape.py:251: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if value == "circle":
TypeError: an integer is required (got type NoneType)
2.4982  WARNING         Monitor specification not found. Creating a temporary one...
Calibration returned:  {'message': 'validation_result: 0.69 -10.19 17.64  0.44 -3.62 8.02', 'result': 1000}
file_size = 183253
total_wbytes = 183253
displayAPI: Disconnect
ioHub Server Process Completed With Code:  0
['et_data.EDF']
['et_data.EDF']
```

And the file is correctly renamed/moved. Here it is: [test_dist_LH_3.zip](https://github.com/Intrepid-2a/EyeTracking/files/14947061/test_dist_LH_3.zip)

I also tried to put a comment just before shutting down: tracker.comment('testing comments')

**Comment by thartbm** [comment]
Amazing! So the setting of path / file names now works in some form?

We could add some security, but I guess this would be a new issue as well:
- check if the default file is there when the object is initiated (and decide what to do with it)
- check if the target file already exists when moving the default edf file to the desired location

The shutdown function should be run. I'm pretty sure that if it doesn't get run, the edf file doesn't get transmitted. That's why I added a back-up function that just calls shutdown which is run when the object is finally destroyed (in case someone forgets to call the shutdown function). But that didn't work as well, so let's just forget it.

There is no message in the EDF file apart from the ones made by the EyeLink itself. Let's take this up in a different issue though, and close this one. Well, close this one only if you think it is done now.

**Comment by ClementAbb** [comment]
Ok I'm closing this one.
